#ifndef __TELCAN_H
#define __TELCAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

#define TELCAN_GROUP_ID_IMU 0x01

#define TELCAN_UNIQUE_ID_BODY_FRONT 0b0000
#define TELCAN_UNIQUE_ID_BODY_BACK 0b0001
#define TELCAN_UNIQUE_ID_WHEEL_LEFT_FRONT 0b0100
#define TELCAN_UNIQUE_ID_WHEEL_LEFT_BACK 0b0101
#define TELCAN_UNIQUE_ID_WHEEL_RIGHT_FRONT 0b0110
#define TELCAN_UNIQUE_ID_WHEEL_RIGHT_BACK 0b0111

#define TELCAN_PACKET_TYPE_ACCEL 0b0001
#define TELCAN_PACKET_TYPE_GYRO 0b0010
#define TELCAN_PACKET_TYPE_TEMP 0b0011
#define TELCAN_PACKET_TYPE_ACCEL_HIGHRES 0b0101
#define TELCAN_PACKET_TYPE_GYRO_HIGHRES 0b0110
#define TELCAN_PACKET_TYPE_TEMP_HIGHRES 0b0111

#ifdef __cplusplus
}
#endif

#endif /* __TELCAN_H */
